# Generated by Django 4.2 on 2023-04-27 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 28, 2, 1, 46, 53312)),
        ),
        migrations.AddField(
            model_name='venues',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 28, 2, 1, 46, 53312)),
        ),
    ]
